project:
  type: website
  output-dir: docs

website:
  title: "Data Visualization with ggplot"
  twitter-card: true
  sidebar:
    background: primary
    # logo: "images/logo.png"
    search: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Arvindiyer/data_visualization_with_ggplot
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Course Description
      - href: schedule.qmd
        text: Schedule
      - section: Materials
        contents:
              - text: Introduction
                href: materials/introduction.qmd
      - href: https://github.com/Arvindiyer/data_visualization_with_ggplot/discussions
        text: Discussions Forum

#  page-footer:
#      border: false
#      center: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
#      right: "&copy; Copyright 2024, Arvind Iyer"
#      background: 
  back-to-top-navigation: true
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto